Various fixes
MelonCode/X-Mas pull request #10
Opened 2020-12-02 10:06 UTC by LoneDev6

- firework damage protection
- fixed exploit: heads getting dropped using water

2020-12-02 10:18 UTC, Aurelien30000 approved these changes

2020-12-02 10:27 UTC, Aurelien30000 requested changes

2020-12-02 10:27 UTC, Aurelien30000 commented on src/main/java/ru/meloncode/xmas/Events.java
> +import org.bukkit.entity.Firework;
Firework import unused, remove it.

2020-12-02 11:17 UTC, LoneDev6 commented
Done

2020-12-08 12:43 UTC, MelonCode approved these changes

2020-12-08 13:28 UTC, merged